replicaCount: 1

backend:
  image: shreybatra/sample-backend
  port: 8000
  serviceType: ClusterIP
  redisUri: redis://redis-svc:6379

frontend:
  image: shreybatra/sample-frontend
  port: 5173
  serviceType: NodePort
  nodePort: 31000
  backendUrl: http://backend-svc:8000

redis:
  image: redis
  port: 6379
  serviceType: ClusterIP

service:
  port: 8000

